apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec: # specificity
  accessModes: 
    - ReadWriteOnce  #Can be read by one single node at time
  resources:
    requests:
      storage: 2Gi
