apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: themindset/multi-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379' # must be setting as a string
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432' # must be setting as a string
            - name: PGDATABASE
              value: postgres
            # kubectl create secret generic pgpassword --from-literal=POSTGRES_PASSWORD=postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword # refer to the "NAME" pgpassword
                  key: POSTGRES_PASSWORD # refer to "KEY" POSTGRES_PASSWORD